defaults:
  - model: hifi
  - metrics: example
  - datasets: inf # we do not want to run inference on training data
  - dataloader: inf
  - _self_
inferencer:
  device_tensors: ["waveform", "mel_spec"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "predict_wavs" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "to_download/model_best_hifi.pth" # path to the pretrained model
  text_query: ""
